name: Github Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: alexanderepstein/Snake-README-Action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit file
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "update contribution snake"
          git push
